# Define the "cinder-volume-powermax-secrets" Secret that contains sensitive
# information pertaining to the [powermax-iscsi] backend.
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-powermax-secrets
type: Opaque
stringData:
  powermax-secrets.conf: |
    [powermax-iscsi]
    san_ip = 10.225.104.114
    san_login = smc
    san_password = smc
