apiVersion: cinder.openstack.org/v1beta1
kind: CinderAPI
metadata:
  name: cinderapi-sample
spec:
  # TODO(user): Add fields here
  #tls:
  #  api:
  #    # secret holding tls.crt and tls.key for the APIs internal k8s service
  #    internal:
  #      secretName: cert-internal-svc
  #    # secret holding tls.crt and tls.key for the APIs public k8s service
  #    public:
  #      secretName: cert-public-svc
  #  # secret holding the tls-ca-bundle.pem to be used as a deploymend env CA bundle
  #  caBundleSecretName: combined-ca-bundle
